### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [devdreamsolution/heroku-laravel-demo#1]
Hi,<br><br>url : https://github.com/devdreamsolution/heroku-laravel-demo/blob/b96ec2462fcb6a41a268a803174a91cdcab2ea6b/config/database.php <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by devdreamsolution** [comment]
:) thank you for your note.
